/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint confirming API status, per-model status, degraded state, and device.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description List available super-resolution models with parameter count and capabilities.
         */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Samples
         * @description List pre-loaded sample tiles with honest geographic and provenance metadata.
         *     Never blocks the main asyncio event loop.
         */
        get: operations["list_samples_api_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples/{sample_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sample Preview
         * @description Small, fast live-inference preview for a sample tile: LR / Bicubic / BharatSR
         *     (/ Ground Truth if available), each as a base64 RGB PNG.
         */
        get: operations["sample_preview_api_samples__sample_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/superresolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Superresolve
         * @description Run super-resolution on an uploaded GeoTIFF or pre-loaded sample tile.
         *     Returns 4x SR result as base64 PNG, multi-spectral views, physical metrics,
         *     and predicted uncertainty map.
         */
        post: operations["superresolve_api_superresolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/superresolve/async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Superresolve Async
         * @description Submit super-resolution as an asynchronous background task.
         *     Returns job_id and status checking URL.
         */
        post: operations["superresolve_async_api_superresolve_async_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare
         * @description Rigorous multi-model benchmark: Bicubic Baseline vs SRCNN vs RCAN side-by-side.
         */
        post: operations["compare_api_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pixel-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pixel Profile
         * @description Extract multi-band spectral reflectance profile at coordinate (x, y).
         */
        post: operations["pixel_profile_api_pixel_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/downstream-masks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Downstream Masks
         * @description Computes binary segmentation masks and real-time IoU/F1 metrics for
         *     downstream analytical tasks (Micro-Canopy Vegetation & Built-Up Infrastructure Extraction).
         */
        post: operations["downstream_masks_api_downstream_masks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Status
         * @description Check asynchronous job status, progress percentage, or retrieve final results.
         */
        get: operations["get_job_status_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Cancel a running or pending asynchronous job.
         */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description List recent background processing jobs.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Superresolve
         * @description Submit multiple tiles for parallel super-resolution.
         *     Returns a batch_id; poll /api/batch/{batch_id} for results.
         *     Max 10 tiles per batch.
         */
        post: operations["batch_superresolve_api_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Batch Status
         * @description Get status and results of all jobs in a batch.
         */
        get: operations["get_batch_status_api_batch__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/geotiff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Geotiff
         * @description Generate and download an authoritative 4-band Float32 GeoTIFF.
         *     Supports either pre-loaded sample_id or an active uploaded run_id.
         *     CRITICAL RULE:
         *     - If the source dataset lacks geospatial metadata, raises HTTP 400 stating
         *       'No geospatial reference available'. Never silently assigns EPSG:4326.
         *     - If georeferenced, preserves exact CRS, scales affine transform for 4x SR (p_out = p_in / 4).
         */
        get: operations["export_geotiff_api_export_geotiff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Report
         * @description Generate an analytical verification report JSON for SIH evaluation.
         *     Reports scientifically defensible metrics without fabricated claims.
         *     Supports either an active run_id (priority, never reruns inference)
         *     or sample_id (runs inference if no run artifact is provided).
         */
        get: operations["export_report_api_export_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/indices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute Indices
         * @description Compute NDVI, NDWI, EVI, SAVI, RVI, NDBI (approx), GCI from super-resolved imagery.
         *     Returns both SR-derived and LR-derived indices for comparison with PNG heatmaps.
         */
        post: operations["compute_indices_api_indices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crop-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crop Health Analysis
         * @description Farmer-facing crop health classification using SR-enhanced spectral indices.
         *     Classifies pixels into 6 agronomic categories and provides actionable recommendations.
         */
        post: operations["crop_health_analysis_api_crop_health_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/field-boundary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Field Boundary Delineation
         * @description Delineate agricultural field boundaries from SR imagery using gradient edge detection on NDVI.
         */
        post: operations["field_boundary_delineation_api_field_boundary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/change-detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Detection
         * @description Bi-temporal change detection between two SR outputs.
         */
        post: operations["change_detection_api_change_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload Model
         * @description Hot-reload a model from an updated checkpoint without server restart.
         *     Security: checkpoint_path must be strictly within the configured weights directory.
         */
        post: operations["reload_model_api_models_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset Summary
         * @description Return aggregated dataset metrics, split proportions, and spatial coverage.
         */
        get: operations["get_dataset_summary_api_dataset_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset Scenes
         * @description Paginated listing of individual scene metadata records.
         */
        get: operations["get_dataset_scenes_api_dataset_scenes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/qa-report/{split}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Qa Report
         * @description Serve the QA verification figure (PNG) for train, val, or test split.
         */
        get: operations["get_qa_report_api_dataset_qa_report__split__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/preprocessing-sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Preprocessing Sample
         * @description Returns step-by-step visual representations of the 4 preprocessing stages:
         *     1. Raw DN capture
         *     2. Radiometric BOA Surface Reflectance [0, 1]
         *     3. Sub-pixel Registration & QA Cleaning
         *     4. 64x64 LR & 256x256 HR Training Pair
         */
        get: operations["get_preprocessing_sample_api_dataset_preprocessing_sample_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/history/{model_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Training History
         * @description Return recorded epoch-by-epoch training metrics or verified final metrics for a model.
         */
        get: operations["get_training_history_api_training_history__model_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/model-card/{model_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model Card
         * @description Return architectural model card, parameter specifications, loss config, and benchmark metrics.
         */
        get: operations["get_model_card_api_training_model_card__model_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/ablations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ablation Comparison
         * @description Surface the 6 scientific ablation configurations comparing loss functions,
         *     architectural capacity, and physical constraints. Loads checkpoint metadata
         *     directly from backend/weights/rcan_ablation_*.pth and verified test reports.
         */
        get: operations["get_ablation_comparison_api_training_ablations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AblationComparisonResponse */
        AblationComparisonResponse: {
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Baseline */
            baseline: string;
            /** Ablations */
            ablations: components["schemas"]["AblationRecord"][];
        } & {
            [key: string]: unknown;
        };
        /** AblationRecord */
        AblationRecord: {
            /** Config Name */
            config_name: string;
            /** Architecture */
            architecture: string;
            /** Checkpoint File */
            checkpoint_file?: string | null;
            /** Epoch */
            epoch?: number | null;
            /** Val Loss */
            val_loss?: number | null;
            /** Parameters Count */
            parameters_count?: number | null;
            /** N Feats */
            n_feats?: number | null;
            /** N Resgroups */
            n_resgroups?: number | null;
            /** N Resblocks */
            n_resblocks?: number | null;
            /** Loss Weights */
            loss_weights?: {
                [key: string]: number;
            } | null;
            /** Psnr Db */
            psnr_db?: number | null;
            /** Ssim */
            ssim?: number | null;
            /** Sam Degrees */
            sam_degrees?: number | null;
            /** Downsample Consistency Mae */
            downsample_consistency_mae?: number | null;
            /** Spectral Mae */
            spectral_mae?: number | null;
            /** Latency Median S */
            latency_median_s?: number | null;
            /** Key Contribution */
            key_contribution: string;
        } & {
            [key: string]: unknown;
        };
        /** AsyncJobSubmitResponse */
        AsyncJobSubmitResponse: {
            /** Status */
            status: string;
            /** Job Id */
            job_id: string;
            /** Model Id */
            model_id: string;
            /** Status Url */
            status_url: string;
        };
        /** BandProfile */
        BandProfile: {
            /** Name */
            name: string;
            /** Band */
            band: string;
            /** Wavelength */
            wavelength: string;
            /** Lr Reflectance */
            lr_reflectance: number;
            /** Bicubic Reflectance */
            bicubic_reflectance?: number | null;
            /** Sr Reflectance */
            sr_reflectance: number;
            /** Hr Reflectance */
            hr_reflectance?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** BatchStatusResponse */
        BatchStatusResponse: {
            /** Batch Id */
            batch_id: string;
            /** Overall Status */
            overall_status: string;
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** Total */
            total: number;
            /** Jobs */
            jobs: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** BatchSubmitResponse */
        BatchSubmitResponse: {
            /** Status */
            status: string;
            /** Batch Id */
            batch_id: string;
            /** Job Ids */
            job_ids: string[];
            /** Total */
            total: number;
            /** Status Url */
            status_url: string;
        } & {
            [key: string]: unknown;
        };
        /** Body_batch_superresolve_api_batch_post */
        Body_batch_superresolve_api_batch_post: {
            /** Files */
            files?: string[];
            /** Sample Ids */
            sample_ids?: string;
            /**
             * Model Id
             * @default rcan
             */
            model_id: string;
            /**
             * Quality
             * @default fast
             */
            quality: string;
        };
        /** Body_change_detection_api_change_detect_post */
        Body_change_detection_api_change_detect_post: {
            /**
             * Run Id T1
             * @description First date run_id (earlier)
             */
            run_id_t1: string;
            /**
             * Run Id T2
             * @description Second date run_id (later)
             */
            run_id_t2: string;
            /**
             * Method
             * @default ndvi_diff
             */
            method: string;
        };
        /** Body_compare_api_compare_post */
        Body_compare_api_compare_post: {
            /** File */
            file?: string;
            /** Sample Id */
            sample_id?: string;
        };
        /** Body_compute_indices_api_indices_post */
        Body_compute_indices_api_indices_post: {
            /** File */
            file?: string;
            /** Sample Id */
            sample_id?: string;
            /** Run Id */
            run_id?: string;
            /**
             * Model Id
             * @default rcan
             */
            model_id: string;
        };
        /** Body_crop_health_analysis_api_crop_health_post */
        Body_crop_health_analysis_api_crop_health_post: {
            /** Sample Id */
            sample_id?: string;
            /** Run Id */
            run_id?: string;
            /**
             * Model Id
             * @default rcan
             */
            model_id: string;
        };
        /** Body_downstream_masks_api_downstream_masks_post */
        Body_downstream_masks_api_downstream_masks_post: {
            /** Sample Id */
            sample_id?: string | null;
            /** Run Id */
            run_id?: string | null;
            /**
             * Model Id
             * @default rcan
             */
            model_id: string;
        };
        /** Body_field_boundary_delineation_api_field_boundary_post */
        Body_field_boundary_delineation_api_field_boundary_post: {
            /** Sample Id */
            sample_id?: string;
            /** Run Id */
            run_id?: string;
            /**
             * Model Id
             * @default rcan
             */
            model_id: string;
            /**
             * Method
             * @default gradient
             */
            method: string;
        };
        /** Body_pixel_profile_api_pixel_profile_post */
        Body_pixel_profile_api_pixel_profile_post: {
            /** Sample Id */
            sample_id?: string | null;
            /** Run Id */
            run_id?: string | null;
            /**
             * X
             * @default 128
             */
            x: number;
            /**
             * Y
             * @default 128
             */
            y: number;
            /**
             * Model Id
             * @default rcan
             */
            model_id: string;
        };
        /** Body_reload_model_api_models_reload_post */
        Body_reload_model_api_models_reload_post: {
            /** Model Id */
            model_id: string;
            /** Checkpoint Path */
            checkpoint_path?: string | null;
        };
        /** Body_superresolve_api_superresolve_post */
        Body_superresolve_api_superresolve_post: {
            /** File */
            file?: string;
            /** Sample Id */
            sample_id?: string;
            /**
             * Model Id
             * @default rcan
             */
            model_id: string;
            /**
             * Quality
             * @default fast
             */
            quality: string;
        };
        /** Body_superresolve_async_api_superresolve_async_post */
        Body_superresolve_async_api_superresolve_async_post: {
            /** File */
            file?: string;
            /** Sample Id */
            sample_id?: string;
            /**
             * Model Id
             * @default rcan
             */
            model_id: string;
            /**
             * Quality
             * @default fast
             */
            quality: string;
        };
        /** ChangeDetectionResponse */
        ChangeDetectionResponse: {
            /** Status */
            status: string;
            /** Run Id T1 */
            run_id_t1: string;
            /** Run Id T2 */
            run_id_t2: string;
            /** Method */
            method: string;
            /** Ndvi Difference Map */
            ndvi_difference_map: string;
            /** Spectral Difference Map */
            spectral_difference_map: string;
            /** Change Magnitude Map */
            change_magnitude_map: string;
            /** Statistics */
            statistics: {
                [key: string]: unknown;
            };
            /** Interpretation */
            interpretation: string;
            /** Disclaimer */
            disclaimer: string;
        } & {
            [key: string]: unknown;
        };
        /** CompareResponse */
        CompareResponse: {
            /** Status */
            status: string;
            /** Run Id */
            run_id?: string | null;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Models */
            models: {
                [key: string]: unknown;
            };
            /** Comparison Table */
            comparison_table: {
                [key: string]: unknown;
            }[];
            /** Ground Truth */
            ground_truth?: {
                [key: string]: unknown;
            } | null;
            /** Geospatial Metadata */
            geospatial_metadata?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** CropHealthResponse */
        CropHealthResponse: {
            /** Status */
            status: string;
            /** Disclaimer */
            disclaimer: string;
            /** Model Id */
            model_id: string;
            /** Classification Map */
            classification_map: string;
            /** Area Statistics */
            area_statistics: {
                [key: string]: unknown;
            };
            /** Health Score */
            health_score: number;
            /** Mean Ndvi */
            mean_ndvi: number;
            /** Mean Evi */
            mean_evi: number;
            /** Sr Vs Lr Ndvi Uplift */
            sr_vs_lr_ndvi_uplift: number;
            /** Recommendations */
            recommendations: string[];
            /** Class Legend */
            class_legend: {
                [key: string]: string;
            };
        } & {
            [key: string]: unknown;
        };
        /** DatasetDateRange */
        DatasetDateRange: {
            /** Min */
            min: string;
            /** Max */
            max: string;
        };
        /** DatasetScenesResponse */
        DatasetScenesResponse: {
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Scenes */
            scenes: components["schemas"]["SceneRecord"][];
        } & {
            [key: string]: unknown;
        };
        /** DatasetSplitCounts */
        DatasetSplitCounts: {
            /** Train */
            train: number;
            /** Val */
            val: number;
            /** Test */
            test: number;
        };
        /** DatasetSummaryResponse */
        DatasetSummaryResponse: {
            /** Total Scenes */
            total_scenes: number;
            splits: components["schemas"]["DatasetSplitCounts"];
            /** Synthetic Count */
            synthetic_count: number;
            /** Real Count */
            real_count: number;
            /** Regions */
            regions: string[];
            /** Sensors */
            sensors: string[];
            date_range: components["schemas"]["DatasetDateRange"];
            /** Mean Cloud Fraction */
            mean_cloud_fraction: number;
            /** Mean Registration Rmse */
            mean_registration_rmse: number;
        } & {
            [key: string]: unknown;
        };
        /** DownstreamMasksResponse */
        DownstreamMasksResponse: {
            /** Status */
            status: string;
            /** Tasks */
            tasks: {
                [key: string]: components["schemas"]["DownstreamTaskItem"];
            };
        } & {
            [key: string]: unknown;
        };
        /** DownstreamTaskItem */
        DownstreamTaskItem: {
            /** Task Name */
            task_name: string;
            /** Description */
            description: string;
            bicubic: components["schemas"]["DownstreamTaskMetrics"];
            rcan: components["schemas"]["DownstreamTaskMetrics"];
            /** Ground Truth Pixel Count */
            ground_truth_pixel_count: number;
            /** Masks */
            masks: {
                [key: string]: string;
            };
        } & {
            [key: string]: unknown;
        };
        /** DownstreamTaskMetrics */
        DownstreamTaskMetrics: {
            /** F1 */
            f1: number;
            /** Iou */
            iou: number;
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
        } & {
            [key: string]: unknown;
        };
        /** EpochMetric */
        EpochMetric: {
            /** Epoch */
            epoch: number;
            /** Loss */
            loss: number;
            /** Psnr */
            psnr?: number | null;
            /** Ssim */
            ssim?: number | null;
            /** Lr */
            lr?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** FieldBoundaryResponse */
        FieldBoundaryResponse: {
            /** Status */
            status: string;
            /** Disclaimer */
            disclaimer: string;
            /** Model Id */
            model_id: string;
            /** Sr Edge Overlay */
            sr_edge_overlay: string;
            /** Lr Edge Overlay */
            lr_edge_overlay: string;
            /** Sr Edge Density */
            sr_edge_density: number;
            /** Lr Edge Density */
            lr_edge_density: number;
            /** Boundary Improvement Ratio */
            boundary_improvement_ratio: number;
            /** Sr Edge Pixel Count */
            sr_edge_pixel_count: number;
            /** Lr Edge Pixel Count */
            lr_edge_pixel_count: number;
            /** Method */
            method: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @example ok
             */
            status: string;
            /**
             * Models Loaded
             * @example 2
             */
            models_loaded: number;
            /**
             * Device
             * @example cpu
             */
            device: string;
            /**
             * Version
             * @example 0.2.0
             */
            version: string;
            /**
             * Active Jobs
             * @default 0
             * @example 0
             */
            active_jobs: number;
            /**
             * Degraded
             * @description True if zero models are loaded
             * @default false
             */
            degraded: boolean;
            /**
             * Models
             * @description Per-model status list
             */
            models?: {
                [key: string]: unknown;
            }[] | null;
        } & {
            [key: string]: unknown;
        };
        /** JobListResponse */
        JobListResponse: {
            /** Jobs */
            jobs: {
                [key: string]: unknown;
            }[];
        };
        /** JobStatusResponse */
        JobStatusResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Model Id */
            model_id: string;
            /**
             * Progress Pct
             * @default 0
             */
            progress_pct: number;
            /**
             * Is Cancelled
             * @default false
             */
            is_cancelled: boolean;
            /** Created At */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Inference Time S */
            inference_time_s?: number | null;
            /** Error Message */
            error_message?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
        };
        /** ModelCardResponse */
        ModelCardResponse: {
            /** Model Name */
            model_name: string;
            /** Architecture */
            architecture: string;
            /** Parameters Count */
            parameters_count: number;
            /** Key Design */
            key_design: string;
            /** Training Config */
            training_config: {
                [key: string]: unknown;
            };
            /** Final Metrics */
            final_metrics: {
                [key: string]: unknown;
            };
            /** Recommended Use */
            recommended_use: string;
        } & {
            [key: string]: unknown;
        };
        /** ModelInfo */
        ModelInfo: {
            /**
             * Id
             * @example rcan
             */
            id: string;
            /**
             * Name
             * @example Residual Channel Attention Network (RCAN)
             */
            name: string;
            /**
             * Scale Factor
             * @default 4
             * @example 4
             */
            scale_factor: number;
            /**
             * Device
             * @default cpu
             * @example cpu
             */
            device: string;
            /** Architecture */
            architecture?: string | null;
            /**
             * N Bands
             * @default 4
             */
            n_bands: number | null;
            /** Epoch */
            epoch?: unknown | null;
            /** Val Loss */
            val_loss?: number | null;
            /**
             * Has Uncertainty
             * @default false
             */
            has_uncertainty: boolean;
            /**
             * Supports Uncertainty
             * @default false
             */
            supports_uncertainty: boolean;
            /** Parameters */
            parameters?: number | null;
            /** Description */
            description?: string | null;
            /**
             * Status
             * @default loaded
             */
            status: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ModelReloadResponse */
        ModelReloadResponse: {
            /** Status */
            status: string;
            /** Model Id */
            model_id: string;
            /** Checkpoint */
            checkpoint: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** ModelsListResponse */
        ModelsListResponse: {
            /** Models */
            models: components["schemas"]["ModelInfo"][];
        };
        /** PixelProfileResponse */
        PixelProfileResponse: {
            /** Status */
            status: string;
            /** Sample Id */
            sample_id?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Model Id */
            model_id: string;
            /** Hr Coordinates */
            hr_coordinates: {
                [key: string]: number;
            };
            /** Lr Coordinates */
            lr_coordinates: {
                [key: string]: number;
            };
            /** Bands Data */
            bands_data: components["schemas"]["BandProfile"][];
            /** Ndvi */
            ndvi: {
                [key: string]: number | null;
            };
            /** Spectral Angle Deg */
            spectral_angle_deg?: number | null;
            /** Surface Classification */
            surface_classification: string;
            /** Signature Analysis */
            signature_analysis: string;
            /**
             * Interpretation Disclaimer
             * @default Rule-based spectral interpretation (heuristic, not ground truth)
             */
            interpretation_disclaimer: string;
        } & {
            [key: string]: unknown;
        };
        /** PreprocessingSampleResponse */
        PreprocessingSampleResponse: {
            /** Scene Id */
            scene_id: string;
            /** Region */
            region: string;
            /** Stages */
            stages: components["schemas"]["PreprocessingStageInfo"][];
            /** Training Pair */
            training_pair: {
                [key: string]: string;
            };
        } & {
            [key: string]: unknown;
        };
        /** PreprocessingStageInfo */
        PreprocessingStageInfo: {
            /** Stage */
            stage: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Image */
            image: string;
        };
        /** ReportResponse */
        ReportResponse: {
            /** Title */
            title: string;
            /** Problem Statement */
            problem_statement: string;
            /** Target Organization */
            target_organization: string;
            /** Sample Id */
            sample_id?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Model Id */
            model_id: string;
            /** Scale Factor */
            scale_factor: string;
            /** Input Dimension */
            input_dimension: number[];
            /** Output Dimension */
            output_dimension: number[];
            /** Latency Seconds */
            latency_seconds: number;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Uncertainty Summary */
            uncertainty_summary?: {
                [key: string]: unknown;
            } | null;
            /** Spectral Integrity Compliance */
            spectral_integrity_compliance: {
                [key: string]: unknown;
            };
            /** Geospatial Metadata */
            geospatial_metadata?: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at?: string | null;
            /** Quality */
            quality?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** SampleInfo */
        SampleInfo: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Title */
            title: string;
            /** Region */
            region: string;
            /** Description */
            description: string;
            /** Tactical Category */
            tactical_category: string;
            /** Coordinates */
            coordinates: string;
            /** Bands */
            bands: number;
            /** Lr Size */
            lr_size: string;
            /** Has Ground Truth */
            has_ground_truth: boolean;
            /**
             * Has Reference
             * @default true
             */
            has_reference: boolean;
            /**
             * Is Independent Hr
             * @default false
             */
            is_independent_hr: boolean;
            /**
             * Reference Type
             * @default none
             */
            reference_type: string;
            /**
             * Reference Provenance
             * @default No reference available
             */
            reference_provenance: string;
            /** Acquisition Date */
            acquisition_date?: string | null;
            /** Gsd */
            gsd?: string | null;
            /** Has Geo */
            has_geo: boolean;
            /** Crs */
            crs?: string | null;
            /** Sensor */
            sensor?: string | null;
            /** Thumbnail */
            thumbnail: string;
            /** Views */
            views: {
                [key: string]: string;
            };
        } & {
            [key: string]: unknown;
        };
        /** SamplesListResponse */
        SamplesListResponse: {
            /** Samples */
            samples: components["schemas"]["SampleInfo"][];
        };
        /** SceneRecord */
        SceneRecord: {
            /** Scene Id */
            scene_id: string;
            /** Region */
            region: string;
            /** Date */
            date: string;
            /** Split */
            split: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /** Source Dataset */
            source_dataset: string;
            /** Sensor */
            sensor: string;
            /** Cloud Fraction */
            cloud_fraction: number;
            /** Registration Rmse */
            registration_rmse: number;
            /** Crs */
            crs?: string | null;
            /** Reflectance Range */
            reflectance_range?: number[] | null;
        } & {
            [key: string]: unknown;
        };
        /** SpectralIndicesResponse */
        SpectralIndicesResponse: {
            /** Status */
            status: string;
            /** Indices */
            indices: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** SuperResolveResponse */
        SuperResolveResponse: {
            /** Status */
            status: string;
            /** Model Id */
            model_id: string;
            /** Run Id */
            run_id?: string | null;
            /** Inference Time S */
            inference_time_s: number;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Output */
            output: {
                [key: string]: unknown;
            };
            /** Bicubic */
            bicubic?: {
                [key: string]: unknown;
            } | null;
            /** Error Map */
            error_map?: {
                [key: string]: unknown;
            } | null;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            uncertainty?: components["schemas"]["UncertaintyOutput"] | null;
            /** Ground Truth */
            ground_truth?: {
                [key: string]: unknown;
            } | null;
            /** Geospatial Metadata */
            geospatial_metadata?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** TrainingHistoryResponse */
        TrainingHistoryResponse: {
            /** Model Name */
            model_name: string;
            /** Is Final Only */
            is_final_only: boolean;
            /** Epochs */
            epochs: components["schemas"]["EpochMetric"][];
            /** Final Metrics */
            final_metrics: {
                [key: string]: unknown;
            };
            /** Summary Note */
            summary_note?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** UncertaintyOutput */
        UncertaintyOutput: {
            /** Image */
            image: string;
            summary: components["schemas"]["UncertaintySummary"];
        } & {
            [key: string]: unknown;
        };
        /** UncertaintySummary */
        UncertaintySummary: {
            /** Mean Uncertainty */
            mean_uncertainty: number;
            /** Max Uncertainty */
            max_uncertainty: number;
            /** Min Uncertainty */
            min_uncertainty: number;
            /** High Uncertainty Pixel Pct */
            high_uncertainty_pixel_pct: number;
            /**
             * Calibration Status
             * @default predicted uncertainty (uncalibrated until empirical validation)
             */
            calibration_status: string;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsListResponse"];
                };
            };
        };
    };
    list_samples_api_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamplesListResponse"];
                };
            };
        };
    };
    sample_preview_api_samples__sample_id__preview_get: {
        parameters: {
            query?: {
                crop?: number;
            };
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    superresolve_api_superresolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_superresolve_api_superresolve_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuperResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    superresolve_async_api_superresolve_async_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_superresolve_async_api_superresolve_async_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncJobSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_compare_api_compare_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pixel_profile_api_pixel_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_pixel_profile_api_pixel_profile_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PixelProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    downstream_masks_api_downstream_masks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_downstream_masks_api_downstream_masks_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownstreamMasksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
        };
    };
    batch_superresolve_api_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_batch_superresolve_api_batch_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_status_api_batch__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_geotiff_api_export_geotiff_get: {
        parameters: {
            query?: {
                /** @description Sample ID to export */
                sample_id?: string | null;
                /** @description Active run ID to export */
                run_id?: string | null;
                /** @description Model to generate SR with */
                model_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_report_api_export_report_get: {
        parameters: {
            query?: {
                /** @description Sample ID */
                sample_id?: string | null;
                /** @description Active run ID to export without rerunning */
                run_id?: string | null;
                /** @description Model ID */
                model_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_indices_api_indices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_compute_indices_api_indices_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpectralIndicesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crop_health_analysis_api_crop_health_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_crop_health_analysis_api_crop_health_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CropHealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    field_boundary_delineation_api_field_boundary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_field_boundary_delineation_api_field_boundary_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldBoundaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_detection_api_change_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_change_detection_api_change_detect_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeDetectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reload_model_api_models_reload_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_reload_model_api_models_reload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelReloadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_summary_api_dataset_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummaryResponse"];
                };
            };
        };
    };
    get_dataset_scenes_api_dataset_scenes_get: {
        parameters: {
            query?: {
                split?: string | null;
                region?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetScenesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_qa_report_api_dataset_qa_report__split__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                split: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preprocessing_sample_api_dataset_preprocessing_sample_get: {
        parameters: {
            query?: {
                scene_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreprocessingSampleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_training_history_api_training_history__model_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_card_api_training_model_card__model_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ablation_comparison_api_training_ablations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AblationComparisonResponse"];
                };
            };
        };
    };
}
